[meta]
title = "Django Voice Agent"
description = "Get started using Deepgram's Voice Agent with this Django demo app"
author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
repository = "https://github.com/deepgram-starters/django-voice-agent"
useCase = "Voice Agent"
language = "Python"
framework = "Django"
sdk = "N/A"
